### ISSUE TITLE
Add back tutorials index

### ISSUE THREAD

**Issue by alanchrt** [smallstep/docs#21]
We used to have a list of all the tutorials on the index page (`/docs/tutorials`). This needs to be resurrected.

**Comment by tashian** [comment]
@C-Mejlak is it possible with MDX to pull in nav links from the Tutorials section of the sidenav into the [Tutorials index page](https://smallstep.com/docs/tutorials/index.html)?

**Comment by C-Mejlak** [comment]
@tashian we might be able to do that, not 100% sure. I imagine we want to do this so that any  changes in the sidebar tutorials section, are automatically reflected, right?

And how would we want to display this, as an unordered list, like below?

![image](https://github.com/smallstep/docs/assets/39129161/cce9c007-1e08-4b02-ad7b-6ad726c04858)

**Comment by tashian** [comment]
@C-Mejlak yes, that would be the idea.
If it's simple, let's do it!
I think it can be like a table of contents, an unordered list of links without the bullets in other words.

**Comment by C-Mejlak** [comment]
Seems I'm not able to push to the repo. This is now on live and can be used anywhere in the docs.

```jsx
<TutorialsList title="Tutorials" />
```

`title` is optional.

**Comment by tashian** [comment]
Thanks @C-Mejlak, I've added a PR to add the tag to the tutorials index page!
